[project]
name = "mcframework-gpu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.7.0",
    "numpy>=1.24.0",
    "torch>=2.1.0",
]
